name: Descarga precio de hoy

on:
  workflow_dispatch:
  schedule:
    - cron: 10,40 6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21 * * *

env:
  GASOLINA_CHAT_ID: ${{ secrets.GASOLINA_CHAT_ID }}
  DIESEL_CHAT_ID: ${{ secrets.DIESEL_CHAT_ID }}
  TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
  FUEL_STATION_ID: 12658
  FUEL_STATION_ID_2: 14386

jobs:
  downloadStatus:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js version 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run download-today
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add report for today
        file_pattern: 'data.json'
    - name: "Run if changes have been detected"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run: npm run send
